name: Deploy to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main  # Se ejecuta en cada push a la rama `main`
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar AWS CLI con credenciales
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia si el bucket está en otra región

    # 3. Sincronizar archivos con el bucket S3
    - name: Sync files to S3
      run: |
        aws s3 sync . s3://prueba1-desafiolatam --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # 4. Invalidar la caché de CloudFront
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation --distribution-id EXXI0M42WFLHC --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
